<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version Condition="'$(Version)' == ''">0.0.0-dev</Version>
    <InformationalVersion>$(Version)</InformationalVersion>
    <PublishReadyToRun>true</PublishReadyToRun>
    <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/Cli/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="PioneerConverter.Core.csproj" />
    <ProjectReference Include="PioneerConverter.Infrastructure.Thermo.csproj" />
  </ItemGroup>

  <Target Name="CopyAllFiles" BeforeTargets="Build">
    <ItemGroup>
      <LibFiles Include="Libs\**\*.dll;Libs\**\*.so;Libs\**\*.dylib" />
    </ItemGroup>
    <Copy SourceFiles="@(LibFiles)" DestinationFiles="@(LibFiles->'$(OutputPath)\lib\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <Target Name="CopyAllFilesOnPublish" BeforeTargets="Publish">
    <ItemGroup>
      <LibFiles Include="Libs\**\*.dll;Libs\**\*.so;Libs\**\*.dylib" />
    </ItemGroup>
    <Copy SourceFiles="@(LibFiles)" DestinationFiles="@(LibFiles->'$(PublishDir)\lib\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <Target Name="RemoveNonRuntimeFiles" AfterTargets="Build">
    <ItemGroup>
      <UnneededFiles Include="$(OutputPath)\*.xml;$(OutputPath)\*.pdb;$(OutputPath)\*.nupkg" />
    </ItemGroup>
    <Delete Files="@(UnneededFiles)" />
  </Target>

  <Target Name="RemoveNonRuntimeFilesOnPublish" AfterTargets="Publish">
    <ItemGroup>
      <UnneededFiles Include="$(PublishDir)\*.xml;$(PublishDir)\*.pdb;$(PublishDir)\*.nupkg" />
    </ItemGroup>
    <Delete Files="@(UnneededFiles)" />
  </Target>
</Project>
