name: Build Installers

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install the Apple certificate and provisioning profile
        if: matrix.os == 'macos-latest'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERT_P12 }}
          P12_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          INSTALLER_CERT_BASE64: ${{ secrets.MACOS_INSTALLER_CERT_P12 }}
          INSTALLER_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          INSTALLER_CERT_PATH=$RUNNER_TEMP/installer_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          echo -n "$INSTALLER_CERT_BASE64" | base64 --decode -o $INSTALLER_CERT_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $INSTALLER_CERT_PATH -P "$INSTALLER_CERT_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # login keychain so signing tools can locate the certificate
          security list-keychains -d user -s $KEYCHAIN_PATH login.keychain

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - uses: apple-actions/import-codesign-certs@v2
        if: matrix.os == 'macos-latest'
        with:
          p12-file-base64: ${{ secrets.MACOS_CERT_P12 }}
          p12-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain: signing_temp

      - uses: apple-actions/import-codesign-certs@v2
        if: matrix.os == 'macos-latest'
        with:
          p12-file-base64: ${{ secrets.MACOS_INSTALLER_CERT_P12 }}
          p12-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain-password: ${{ secrets.MACOS_CERT_PASSWORD }}
          keychain: signing_temp
          create-keychain: false

      - name: List codesigning identities
        if: matrix.os == 'macos-latest'
        run: 
          security find-identity -v -p codesigning
          security find-identity -v -p basic

      - name: Install Inno Setup
        if: matrix.os == 'windows-latest'
        run: choco install innosetup -y

      - name: Build installers
        run: ./build_installers.sh
        shell: bash
        env:
          CODESIGN_IDENTITY: ${{ secrets.CODESIGN_IDENTITY }}
          PKG_SIGN_IDENTITY: ${{ secrets.PKG_SIGN_IDENTITY }}

      - name: Notarize macOS package
        if: matrix.os == 'macos-latest'
        env:
          AC_USERNAME: ${{ secrets.NOTARIZE_APPLE_ID }}
          AC_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}
          TEAM_ID: ${{ secrets.NOTARIZE_TEAM_ID }}
        run: |
          xcrun notarytool store-credentials notary-profile \
            --apple-id "$AC_USERNAME" \
            --team-id "$TEAM_ID" \
            --password "$AC_PASSWORD"
          for pkg in installers/macos/PioneerConverter-*.pkg; do
            echo "Submitting $pkg"
            result=$(xcrun notarytool submit "$pkg" \
              --keychain-profile notary-profile --wait --output-format json)
            echo "$result"
            status=$(echo "$result" | grep -o '"status" *: *"[^"]*"' | head -n1 | sed 's/.*"status" *: *"\([^"]*\)"/\1/')
            subid=$(echo "$result" | grep -o '"id" *: *"[^"]*"' | head -n1 | sed 's/.*"id" *: *"\([^"]*\)"/\1/')
            if [ "$status" != "Accepted" ]; then
              echo "Notarization failed for $pkg with status $status"
              xcrun notarytool log "$subid" --keychain-profile notary-profile
              exit 1
            fi
          done
            
      - name: Staple notarization ticket
        if: matrix.os == 'macos-latest'
        run: |
          for pkg in installers/macos/PioneerConverter-*.pkg; do
            xcrun stapler staple "$pkg"
          done
          


      - name: Upload binary (linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: binary-linux-x64
          path: dist/PioneerConverter-linux-x64.zip

      - name: Upload installer (linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: installer-linux
          path: installers/linux/PioneerConverter_*_amd64.deb

      - name: Upload binary (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: binary-win-x64
          path: dist/PioneerConverter-win-x64.zip

      - name: Upload installer (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: installer-windows
          path: installers/windows/PioneerConverter-Setup.exe

      - name: Upload binary (mac arm64)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: binary-mac-arm64
          path: dist/PioneerConverter-osx-arm64.zip

      - name: Upload binary (mac x64)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: binary-mac-x64
          path: dist/PioneerConverter-osx-x64.zip

      - name: Upload installer (mac arm64)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: installer-mac-arm64
          path: installers/macos/PioneerConverter-arm64.pkg

      - name: Upload installer (mac x64)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: installer-mac-x64
          path: installers/macos/PioneerConverter-x64.pkg

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release view "$tag" >/dev/null 2>&1 || \
            gh release create "$tag" -t "$tag" -n "Release $tag"

      - name: Upload binaries to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          for file in artifacts/binary-*/*; do
            gh release upload "$tag" "$file" --clobber
          done

      - name: Upload installers to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          for file in artifacts/installer-*/*; do
            gh release upload "$tag" "$file" --clobber
          done

